  version: '2.21.0'

  services:

    stdan:
      build:
        context: .devcontainer/
        dockerfile: Dockerfile
      container_name: 'stdan'
      stdin_open: true
      tty: true
      volumes:
        - ./:/app

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #         - count: 1
    #         - capabilities: [gpu]